### ISSUE TITLE
Functional Group Filter: SMARTS pattern issues / bugs

### ISSUE THREAD

**Issue by kienerj** [rdkit/knime-rdkit#39]
There seems to be an issue(s) with the halogen patterns. First one I have observed some time ago. It seems CF3 is not filtered out.  Example:

CC12C3C11CCC2OC3(C)CC1C(F)(F)F

(All examples are from GDB-17)

If I set F to < 3, I expect these molecules to be filtered out.

Second problem is related Bromine but probably also would affect all other halogens. In this specific setting I have halogens set to 0 and non fluorine halogens also set to 0. Yeah it's redundant (configurable subnode) but maybe affects the issue.

molecules passing this filter:

BrC1=NC2=C(NS1(=O)=O)SC(=C2)C#C

BrC1=NC=C2N3C(=CS2(=O)=O)C=COC=C13

Many more from GDB-17

So there seems to be an issue with the SMARTS pattern. I'm especially confused by the complexity of the Top halogen pattern. Couldn't that just be [F,Cl, Br,I]? Or what am I missing?

**Comment by greglandrum** [comment]
@kienerj : the SMARTS definitions used are intended to identify functional groups in the sense of reactivity. When we assembled this set we were specifically asked to exclude things like `-CF3` or `-CCl3`. I realize that this is somewhat confusing, so I'll try and come up with some improvements for the documentation.

**Comment by greglandrum** [comment]
The case of the bromines is more complicated.
The piece of the generic halogen pattern that rules out your two examples is:
`!$([F,Cl,Br,I]-[C,S](=[O,S,N]))`
This is intended to make it so that things like acid chlorides don't match as halogens, but the SMARTS isn't specific enough - it should be: `!$([F,Cl,Br,I]-[C,S](=[D1;O,S,N]))`
I'll fix this.
